# Generated by Django 5.0.1 on 2025-02-20 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patientreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreg',
            name='blood_group',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='patientreg',
            name='disease',
            field=models.CharField(blank=True, default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientreg',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patientreg',
            name='habits',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='patientreg',
            name='medical_history',
            field=models.TextField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientreg',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
