# Generated by Django 5.0.1 on 2025-02-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_patientreg_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreg',
            name='disease',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientreg',
            name='medical_history',
            field=models.TextField(default='None'),
        ),
    ]
