# Generated by Django 5.0.1 on 2025-02-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_patientreg_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreg',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=10),
        ),
    ]
