# Generated by Django 5.0.1 on 2025-03-05 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_staff_workinghour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='previous_timings',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='working_hours_end',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='working_hours_start',
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='years_of_experience',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staff'),
        ),
    ]
