# Generated by Django 5.0.1 on 2025-03-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_staff_previous_timings_remove_staff_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='StaffD',
        ),
    ]
