# Generated by Django 5.0.1 on 2025-03-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_staffd_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffd',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
