# Generated by Django 5.0.1 on 2025-03-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_nursereg_blood_group_alter_nursereg_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursereg',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
