# Generated by Django 5.0.1 on 2025-03-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_nursereg_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursereg',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
