# Generated by Django 5.0.1 on 2025-03-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_dialysistubing_waterintake_weighttracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='reminders_set',
            field=models.BooleanField(default=False),
        ),
    ]
