# Generated by Django 5.0.1 on 2025-04-08 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_prescription_reminders_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('department', models.CharField(default='Eyecare', max_length=50)),
                ('right_sph', models.DecimalField(decimal_places=2, max_digits=5)),
                ('right_cyl', models.DecimalField(decimal_places=2, max_digits=5)),
                ('right_axis', models.IntegerField()),
                ('right_prism', models.CharField(blank=True, max_length=20, null=True)),
                ('left_sph', models.DecimalField(decimal_places=2, max_digits=5)),
                ('left_cyl', models.DecimalField(decimal_places=2, max_digits=5)),
                ('left_axis', models.IntegerField()),
                ('left_prism', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eye_exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-exam_date'],
            },
        ),
    ]
