# Generated by Django 5.0.1 on 2025-04-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_eyeexam_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='before_after_food',
            field=models.CharField(choices=[('before', 'Before Food'), ('after', 'After Food'), ('none', 'None')], max_length=10),
        ),
    ]
