# Generated by Django 5.0.1 on 2025-04-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_bloodpressurereading'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodpressurereading',
            name='status',
            field=models.CharField(default='Normal', max_length=50),
        ),
    ]
