# Generated by Django 5.0.1 on 2025-04-19 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_bloodpressurereading_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CholesterolReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='Cardiology', max_length=50)),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('total', models.PositiveIntegerField()),
                ('ldl', models.PositiveIntegerField()),
                ('hdl', models.PositiveIntegerField()),
                ('triglycerides', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cholesterol_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cholesterol Reading',
                'verbose_name_plural': 'Cholesterol Readings',
                'ordering': ['-record_date'],
            },
        ),
    ]
