# Generated by Django 5.0.1 on 2025-04-19 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_cholesterolreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECGReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('heart_rate', models.PositiveSmallIntegerField()),
                ('pr_interval', models.PositiveSmallIntegerField()),
                ('qrs_duration', models.PositiveSmallIntegerField()),
                ('qt_interval', models.PositiveSmallIntegerField()),
                ('qtc', models.PositiveSmallIntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecg_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ECG Reading',
                'ordering': ['-record_date'],
            },
        ),
    ]
