# Generated by Django 5.0.1 on 2025-04-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_ecgreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffd',
            name='sub_department',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
