# Generated by Django 5.0.1 on 2025-04-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_staffd_sub_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursereg',
            name='sub_department',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
