# Generated by Django 5.0.1 on 2025-05-02 20:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_nursereg_sub_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-prescribed_at']},
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='reminders_set',
            new_name='reminders_enabled',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='timing',
        ),
        migrations.AddField(
            model_name='prescription',
            name='timing_pattern',
            field=models.CharField(default=False, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescribed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
